- hosts: citrix_adm_service

  gather_facts: False
  collections:
    - citrix.adm

  tasks:
    - name: Login to ADM Service
      delegate_to: localhost
      register: login_result
      citrix_adm_login:
        adm_ip: "{{ adm_host }}"
        is_cloud: true
        id: "{{ client_id }}"
        secret: "{{ client_secret }}"

    # log login_result
    - name: Log login_result
      delegate_to: localhost
      debug:
        var: login_result

    - name: Setup stylebook
      delegate_to: localhost
      citrix_adm_stylebook:
        adm_ip: "{{ adm_host }}"
        is_cloud: true
        nitro_auth_token: "{{ login_result.session_id }}"

        state: present

        name: basic-lb-config
        namespace: com.example.stylebooks
        version: "0.2"

        source: |
          ---
          name: basic-lb-config
          namespace: com.example.stylebooks
          version: "0.1"
          display-name: Load Balancing Configuration
          description: This StyleBook defines a simple load balancing configuration.
          schema-version: "1.0"

          import-stylebooks:
            -
              namespace: netscaler.nitro.config
              version: "10.5"
              prefix: ns

          parameters:
            -
              name: name
              type: string
              label: Application Name
              description: Give a name to the application configuration.
              required: true
            -
              name: ip
              type: ipaddress
              label: Application Virtual IP (VIP)
              description: The Application VIP that clients access
              required: true
            -
              name: lb-alg
              type: string
              label: LoadBalancing Algorithm
              description: Choose the loadbalancing algorithm (method) used for loadbalancing client requests between the application servers.
              allowed-values:
              - ROUNDROBIN
              - LEASTCONNECTION
              default: ROUNDROBIN
            -
              name: svc-servers
              type: ipaddress[]
              label: Application Server IPs
              description: The IP addresses of all the servers of this application
              required: true
            -
              name: svc-port
              type: tcp-port
              label: Server Port
              description: The TCP port open on the Application Servers to receive requests.
              default: 80

          components:
            -
              name: lbvserver-comp
              type: ns::lbvserver
              properties:
                name: $parameters.name + "-lb"
                servicetype: HTTP
                ipv46: $parameters.ip
                port: 80
                lbmethod: $parameters.lb-alg

              components:
                -
                  name: svcg-comp
                  type: ns::servicegroup
                  properties:
                    servicegroupname: $parameters.name + "-svcgrp"
                    servicetype: HTTP

                  components:
                    -
                      name: lbvserver-svg-binding-comp
                      type: ns::lbvserver_servicegroup_binding
                      properties:
                        name: $parent.parent.properties.name
                        servicegroupname: $parent.properties.servicegroupname
                    -
                      name: members-svcg-comp
                      type: ns::servicegroup_servicegroupmember_binding
                      repeat: $parameters.svc-servers
                      repeat-item: srv
                      properties:
                        ip: $srv
                        port: $parameters.svc-port
                        servicegroupname: $parent.properties.servicegroupname

          outputs:
            -
              name: lbvserver-comp
              value: $components.lbvserver-comp
              description: The component that builds the Nitro lbvserver configuration object
            -
              name: servicegroup-comp
              value: $components.lbvserver-comp.components.svcg-comp
              description: The component that builds the Nitro servicegroup configuration object

    - name: Logout from ADM Service
      delegate_to: localhost
      citrix_adm_logout:
        adm_ip: "{{ adm_host }}"
        is_cloud: true
        nitro_auth_token: "{{ login_result.session_id }}"
