- hosts: citrix_adc

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.citrixadc_modules


  tasks:
    - name: setup appfw settings
      delegate_to: localhost
      citrix_adc_appfw_learningsettings:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        validate_certs: no

        state: present

        profilename: test_profile
        starturlminthreshold: 30
