---
- hosts: citrix_adc

  gather_facts: False
  collections:
    - citrix.citrixadc_modules

  tasks:

    - name: Setup service
      delegate_to: localhost
      citrix_adc_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present
        name: service-http
        servicetype: HTTP
        ipaddress: 172.18.0.4
        port: 5000
